org: istio
repo: bots
image: 678412441677.dkr.ecr.us-west-2.amazonaws.com/ghcr/istio/testing/build-tools:master-80657d56e324b5d8b4a74806bf0979e4b89e99a5

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: deploy-policybot
    cluster: test-infra-trusted
    excluded_requirements: [cache]
    node_selector:
      prod: prow
    service_account_name: prowjob-bots-deployer
    regex: '^policybot/'
    types: [postsubmit]
    command:
    - entrypoint
    - make
    - -C
    - policybot
    - deploy
    requirements: [docker]
